### ISSUE TITLE
Is this allowed in mac app store?

### ISSUE THREAD

**Issue by SkrewEverything** [jrw01/JSystemInfoKit#1]
I just want to know whether using SystemInfoKit is safe for app store?

Thanks!

Great Job! #

**Comment by jrw01** [comment]
@SkrewEverything: Everything in SystemInfoKit except the JSKSMC class is allowed in the App Store. JSKSMC uses undocumented APIs which Apple does not want developers to know about or use (it is possible to cause hardware damage by writing unsafe values to the SMC) and your app will be rejected. 

Note that if you do use SystemInfoKit in your own app, because SystemInfoKit is under the GPL license the source code for the app must also be released under the GPL license. I would also recommend that you include a link to https://jrw01.github.io/systeminfokit.html in the about window of the app.

**Comment by SkrewEverything** [comment]
@jrw01 
I would definitely give credit to you.
Thank you!
